### ISSUE TITLE
Constant functions

### ISSUE THREAD

**Issue by pauliax** [hoqu-io/platform#1]
HoQuPlatform.sol
Functions getLead() and getLeadSecret() could be marked with a keyword "constant" as  they do not modify contract’s state. A constant function can tell you the result without needing a transaction.

**Comment by slash686** [comment]
hi, @pauliax, this is a known issue. This is also valid for getNetwork() and getOffer() methods as they are also not causing any state change.

However, please note that following statement is not 100% correct:

> A constant function can tell you the result without needing a transaction.

please see this [link](https://ethereum.stackexchange.com/questions/13851/could-we-call-a-constant-function-without-spending-any-gas-inside-a-transaction/13853) for details

thank you
